# You need to run this workflow once
name: "ğŸ¤– Previous PR"
on:
  workflow_dispatch:

jobs:
  triage:
    name: "ğŸ—ï¸ Triage"
    runs-on: ubuntu-latest
    timeout-minutes: 1
    permissions:
      contents: read
      pull-requests: write

    steps:
    
    # Label PRs 1, 2, and 3
    - uses: actions/labeler@v4
      name: "ğŸ”– Labeler"
      with:        
        pr-number: |
          1
          2
          3
